steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['install']
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/instaltec/quickstart-image', '.' ]
images:
  - 'gcr.io/instaltec/quickstart-image'